### ISSUE TITLE
does not work with scheduler

### ISSUE THREAD

**Issue by sdmydbr9** [MMRIZE/MMM-CalendarExt3Journal#2]
the module works fine by itself but when i try to schedule the module with another module MMM-Scheduler, it does not seem to follow the schedule time and ends up being shown always. 

```
{
  classes: 'scheduler default',
  disabled: false,
  module: "MMM-CalendarExt3Journal",
module_schedule: {from: '0 22 * * *', to: '30 23 * * *'},
  position: "middle_center",
        config: {
    hourLength: 12,
    beginHour:  8,
    height: '750px',
    width: '100%',
                }
},

```

after using the above config, it is supposed to be shown only between 10 pm and 11:30 pm but it ends up being shown always, but other module works just fine with the schedule. Might be a bug here?

**Comment by eouia** [comment]
I have no idea what MMM-Scheduler. Can you show me the link?

**Comment by eouia** [comment]
What you mean was [MMM-ModuleScheduler](https://github.com/ianperrin/MMM-ModuleScheduler)

Then see this; maybe you made a mistake in placing the `module_schedule` property. It seems to have to be placed inside fo `config: {...}`.

**Comment by sdmydbr9** [comment]
hey.. thank you so much for pointing that out, it was silly now that you point it out. :-) ofcourse its working ....
